### ISSUE TITLE
cubbies overlay does not fade away

### ISSUE THREAD

**Issue by maxwell** [copyninja/cubbies-firefox#1]
It has a timeout in chrome, but it seems to stay until the page reloads in firefox

**Comment by copyninja** [comment]
Basically I used the same script as in Chrome nothing changed as I told its a hack as I'm not a js guy :) but I'm trying to rewrite the thing again.

**Comment by copyninja** [comment]
I tried changing -webkit-transitions to -moz-transitions but still no luck :(.. As you told it may be because of wrong parameter some one with better CSS knowledge should help me here
